version: "3.8"

services:
  brewcomp:
    container_name: brewcomp-frontend
    build: ..
    restart: unless-stopped
    ports:
      - ${FRONTEND_PORT}:80/tcp
      - ${FRONTEND_HTTPS_PORT}:443/tcp
    env_file: ../.env
